config/routes.rb
RailsProj::Application.routes.draw do
  root :to => 'posts#index'

  resources :posts
  resources :comments
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content

  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :url

  has_many :comments

  before_create :generate_slug

  def to_param
  	slug
  end

  def generate_slug
  	self.slug = title.split(' ').join('_')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	# GET /posts
	def index
		@posts = Post.all

		respond_to do |format|
			format.html
		end
	end

	def show
		@post = Post.where(slug: params[:id]).first

		respond_to do |format|
			format.html
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
	<li>
		<%= link_to "All posts", posts_path %>
	</li>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myapp" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/index.html.erb
<h1>This is all the posts</h1>

<table>
	<tr>
		<td>URL</td>
		<td>Title</td>
		<td>Comments</td>
	</tr>

<% @posts.each do |post| %>
	<tr>
		<td><%= post.url %></td>
		<td><%= link_to post.title, post_path(post) %></td>
		<td><%= post.comments.count %></td>
	</tr>
<% end %>
</table>

app/views/posts/show.html.erb
<h1><%= link_to @post.title, @post.url %></h1>
<%= pluralize(@post.comments.count, "comment") %> !

<ul>
	<% @post.comments.each do |comment| %>
		<li><%= comment.content %></li>
	<% end %>
</ul>

<%= link_to 'Back to all', posts_path %>